kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: console-operator
  namespace: openshift-console
rules:
# TODO: delete is needed for ownerRefs on older clusters
# should remove in the future.
- apiGroups:
  - console.openshift.io
  resources:
  - consoles
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - services
  - events
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: console-operator
rules:
- apiGroups:
  - oauth.openshift.io
  resources:
  - oauthclients
  verbs:
  - get
  - update
  resourceNames:
  - openshift-console
